In [7]:
import numpy as np
from nnfs.datasets import spiral_data
import nnfs

nnfs.init()

In [5]:
class Layer_Dense:
    def __init__(self, input, neuron):
        self.input = input 
        self.neuron = neuron
        self.weights = 0.01 * np.random.randn(input, neuron)  
        self.biases = np.zeros((1, neuron))
    
    def forward(self, input):
        
        # since the weights matrix is input X neuron we don't transpue the weights
        self.output =  np.dot(input, self.weights) + self.biases

In [6]:
class Activation_ReLu:
    def forward(self, input):
        self.output = np.maximum(0, input)

In [8]:
X,y = spiral_data(samples=100, classes=3)

In [11]:
dense1 =  Layer_Dense(2,3)
activation = Activation_ReLu()

In [12]:
dense1.forward(X)
activation.forward(dense1.output)

In [14]:

print(activation.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.83064398e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.000000

In [15]:
print(dense1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.46529817e-05 -2.59559802e-05 -3.92041729e-05]
 [-1.30462300e-04 -1.00681449e-04 -9.42240658e-05]
 [-3.33566830e-04 -2.20894930e-04 -1.28127926e-04]
 [-4.34181566e-04 -2.91181233e-04 -1.78067363e-04]
 [ 3.83064398e-05 -2.73519145e-05 -1.48063002e-04]
 [-5.75769925e-04 -4.02813632e-04 -2.87628121e-04]
 [-4.16442868e-04 -3.29026516e-04 -3.24375666e-04]
 [-5.69526630e-04 -4.30042244e-04 -3.82067199e-04]
 [-8.81730230e-04 -6.13157405e-04 -4.29020613e-04]
 [-9.60246660e-04 -6.71670830e-04 -4.79305745e-04]
 [-1.23522116e-03 -7.70617160e-04 -3.28199356e-04]
 [-1.36802159e-03 -8.84342124e-04 -4.58814262e-04]
 [-1.42687163e-03 -9.51779541e-04 -5.69310563e-04]
 [-1.59880077e-03 -1.02719082e-03 -5.16651373e-04]
 [-1.71263132e-03 -1.09316048e-03 -5.31316618e-04]
 [-1.38725876e-03 -7.80616538e-04 -1.06604144e-04]
 [-1.94019149e-03 -1.25032535e-03 -6.38702302e-04]
 [-1.95132731e-03 -1.19146158e-03 -4.38461226e-04]
 [-2.14168173e-03 -1.40433467e-